name: smart_waste_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core:   ^3.13.0
  firebase_auth:   ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  # State management
  provider: ^6.0.1

  # UI
  cupertino_icons: ^1.0.8
  google_fonts:    ^6.2.1

  # Camera
  camera: ^0.11.1                # use the latest published 0.11.x (0.10.6+2 doesn’t exist!) :contentReference[oaicite:0]{index=0}

  # Image processing for TFLite
  image: ^3.3.0                  # aligns with flutter_launcher_icons and image package for preprocessing
  image_picker: ^1.0.4
  
  # On‐device ML
  tflite_flutter: ^0.11.0        # keep TFLite interpreter
  # remove tflite_flutter_helper → it only supports tflite_flutter <=0.9.0 :contentReference[oaicite:1]{index=1}

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:            ^5.4.2
  build_runner:       ^2.4.0
  flutter_lints:      ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/model.tflite
    - assets/labels.txt

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
